from __future__ import annotations

from dataclasses import dataclass

import constants


SEGMENT_FRAMES_BEFORE_TAKEOFF = 160
SEGMENT_FRAMES_AFTER_TAKEOFF = 200
TYPE_WINDOW_START = 0
TYPE_WINDOW_FRAMES = 200
TYPE_WINDOW_OFFSET = -40
SUCCESS_WINDOW_FRAMES = 180
SUCCESS_WINDOW_START = SEGMENT_FRAMES_BEFORE_TAKEOFF + (SEGMENT_FRAMES_AFTER_TAKEOFF - SUCCESS_WINDOW_FRAMES)
JUMP_WINDOW_FRAMES = SEGMENT_FRAMES_BEFORE_TAKEOFF + SEGMENT_FRAMES_AFTER_TAKEOFF

DEFAULT_DETECTION_THRESHOLD = constants.treshold
DEFAULT_SMOOTHING_SIGMA = 30
DEFAULT_COMBINATION_GAP_FRAMES = 180
GYRO_SATURATION_WARNING_THRESHOLD = 1900.0
ACCELERATION_ABERRANT_LIMIT_G = 32.0

ROTATION_MIRROR_COLUMNS = ("Euler_X", "Gyr_X")


@dataclass(frozen=True)
class DetectionConfig:
    threshold: float = DEFAULT_DETECTION_THRESHOLD
    smoothing_sigma: float = DEFAULT_SMOOTHING_SIGMA
    combination_gap_frames: int = DEFAULT_COMBINATION_GAP_FRAMES


@dataclass(frozen=True)
class TrainingConfig:
    train_ratio: float = 0.8
    augment_mirror: bool = True
